### PR TITLE
Update `:uri_query`

### PR DESCRIPTION
**Pull request by peaceful-james**

### CODE REVIEW

**Comment by peaceful-james** [comment]
I had to update ecto to make the project compile for me.

**Comment by jan-swiatek** [comment]
Hi! Thanks for submitting PR. Could you please create an issue and provide more details about encountered problem?

**Comment by peaceful-james** [comment]
> Hi! Thanks for submitting PR. Could you please create an issue and provide more details about encountered problem?

I can not remember why I had to do this. I created the PR weeks ago and my brain RAM is not that large.

I do see here https://hex.pm/packages/uri_query that the current version is over 7 years old so this seems like a good change based on that alone.

**Comment by jan-swiatek** [comment]
Thank you @peaceful-james. I updated few dependencies (including `ecto` and `uri_query`) in #80.

**Comment by peaceful-james** [comment]
Already done in #80

**Pull request closed without merging**
